/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/MyToolbar copy 2.vue')['default']
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    copy: typeof import('./src/components/MyToolbar copy.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MyAutoComplete: typeof import('./src/components/MyAutoComplete.vue')['default']
    MyDevToolbar: typeof import('./src/components/MyDevToolbar.vue')['default']
    MyDevTools: typeof import('./src/components/MyDevTools.vue')['default']
    MyFooter: typeof import('./src/components/MyFooter.vue')['default']
    MyInput: typeof import('./src/components/MyInput.vue')['default']
    MyLikeButton: typeof import('./src/components/MyLikeButton.vue')['default']
    MyToolbar: typeof import('./src/components/MyToolbar.vue')['default']
    MyWrapper: typeof import('./src/components/MyWrapper.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Summarizer: typeof import('./src/components/Summarizer.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
